# Site settings
title: Mariage de Lise et Benoit
# description: "Nous vous invitons à notre mariage et à séjourner à la suite au gite les blaches à vernous en vivaraix du 21 au 28 juillet."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#251E26'
  links: '#219ab3'

# Build settings
markdown: kramdown
permalink: pretty
